services:

  wallet-service:
    image: openjdk:22-jdk-oracle
    container_name: walletimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    depends_on:
      - wallet-db
    env_file:
      - .env
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/WalletService-v1.1.0.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  wallet-db:
    image: mongo:latest
    container_name: walletdb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_wallet:/etc/mongo
      - mongo_wallet_data:/data/db
      - mongo_wallet_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:


volumes:
  mongo_wallet:
  mongo_wallet_data:
  mongo_wallet_config: